[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
preDeployCommand = "python manage.py migrate --noinput"
startCommand = "./entrypoint.sh"
healthcheckPath = "/api/health/"
healthcheckTimeout = 30
